# Generated by Django 3.0.6 on 2020-05-31 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alliance',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('duration', models.IntegerField()),
                ('startingDate', models.DateField(auto_now=True)),
                ('description', models.TextField(max_length=500)),
                ('allianceType', models.CharField(choices=[('AP', 'Alianza de Producto'), ('AI', 'Alianza de Insumo')], default='AP', max_length=2)),
                ('status', models.CharField(choices=[('A', 'Aceptada'), ('R', 'Rechazada'), ('N', 'En negociación')], default='N', max_length=1)),
                ('disccount', models.FloatField(null=True)),
                ('limitQuantity', models.IntegerField(null=True)),
                ('alliedPercentage', models.FloatField(null=True)),
                ('ownerPercentage', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('nit', models.CharField(max_length=50)),
                ('owner', models.CharField(max_length=100)),
                ('suscription', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
                ('price', models.FloatField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.Category')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.Company')),
            ],
        ),
        migrations.CreateModel(
            name='Preference',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.Category')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.Company')),
                ('sector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.Sector')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('country', models.CharField(default='Colombia', max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Company')),
            ],
        ),
        migrations.AddField(
            model_name='company',
            name='sector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.Sector'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.TextField(max_length=500)),
                ('alliance', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.Alliance')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.Company')),
            ],
        ),
        migrations.AddField(
            model_name='alliance',
            name='allied',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aliado', to='api.Company'),
        ),
        migrations.AddField(
            model_name='alliance',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='propietarioAlianza', to='api.Company'),
        ),
        migrations.AddField(
            model_name='alliance',
            name='products',
            field=models.ManyToManyField(to='api.Product'),
        ),
    ]
