# Generated by Django 3.0.6 on 2020-05-30 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Preference',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='api.Category')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.Company')),
                ('sector', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='api.Sector')),
            ],
        ),
    ]
