# Generated by Django 3.0.6 on 2020-05-31 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_location_country'),
        ('api', '0002_auto_20200530_1933'),
    ]

    operations = [
    ]
