# Generated by Django 3.0.6 on 2020-05-30 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200530_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='nit',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='company',
            name='owner',
            field=models.CharField(max_length=100),
        ),
    ]
