# Generated by Django 3.0.6 on 2020-05-31 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200531_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
    ]
