# Generated by Django 3.0.6 on 2020-05-31 04:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_merge_20200530_1939'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alliance',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('duration', models.IntegerField()),
                ('startingDate', models.DateField(auto_now=True)),
                ('description', models.TextField(max_length=500)),
                ('allianceType', models.CharField(choices=[('AP', 'Alianza de Producto'), ('AI', 'Alianza de Insumo')], default='AP', max_length=2)),
                ('status', models.CharField(choices=[('A', 'Aceptada'), ('R', 'Rechazada'), ('N', 'En negociación')], default='N', max_length=1)),
                ('disccount', models.FloatField()),
                ('limitQuantity', models.IntegerField()),
                ('alliedPercentage', models.FloatField()),
                ('ownerPercentage', models.FloatField()),
                ('allied', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aliado', to='api.Company')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='propietarioAlianza', to='api.Company')),
                ('products', models.ManyToManyField(to='api.Product')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.TextField(max_length=500)),
                ('alliance', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.Alliance')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.Company')),
            ],
        ),
    ]
