# Generated by Django 3.0.6 on 2020-05-31 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200531_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='pictures/'),
        ),
    ]
