# Generated by Django 3.0.6 on 2020-05-31 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alliance_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alliance',
            name='alliedPercentage',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='alliance',
            name='disccount',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='alliance',
            name='limitQuantity',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='alliance',
            name='ownerPercentage',
            field=models.FloatField(blank=True),
        ),
    ]
