# Generated by Django 3.0.6 on 2020-05-31 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20200531_0509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alliance',
            name='alliedPercentage',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='alliance',
            name='disccount',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='alliance',
            name='limitQuantity',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='alliance',
            name='ownerPercentage',
            field=models.FloatField(null=True),
        ),
    ]
